on: [push, pull_request]

name: Testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          #- armv7-unknown-linux-gnueabihf
          #- powerpc64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
    steps:
      - name: Update Apt Repository
        run: sudo apt-get update
      - name: Install Sound
        run: sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
